import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Добавляем 600+ продуктов...');

  const products = [
    // ===== КРУПЫ, КАШИ, МАКАРОНЫ =====
    { name: 'Гречка ядрица (варёная)', brand: 'Увелка', calories: 110, protein: 4.2, fat: 1.1, carbs: 20.6, fiber: 2.7, isPublic: true, isVerified: true },
    { name: 'Гречка зелёная (варёная)', brand: 'Образ жизни', calories: 105, protein: 4.0, fat: 1.0, carbs: 19.5, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Гречка с грибами и луком', brand: '', calories: 130, protein: 5.5, fat: 3.5, carbs: 19.0, fiber: 2.2, isPublic: true, isVerified: true },
    { name: 'Гречка с молоком', brand: '', calories: 145, protein: 5.8, fat: 4.2, carbs: 21.0, fiber: 2.3, isPublic: true, isVerified: true },
    { name: 'Рис белый варёный', brand: 'Мистраль', calories: 116, protein: 2.2, fat: 0.5, carbs: 25.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Рис бурый варёный', brand: 'Мистраль', calories: 112, protein: 2.6, fat: 0.9, carbs: 23.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Рис дикий варёный', brand: 'Мистраль', calories: 101, protein: 4.0, fat: 0.3, carbs: 21.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Рис басмати варёный', brand: 'Мистраль', calories: 120, protein: 2.4, fat: 0.4, carbs: 26.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Рис жасмин варёный', brand: 'Мистраль', calories: 118, protein: 2.3, fat: 0.3, carbs: 26.5, fiber: 0.4, isPublic: true, isVerified: true },
    { name: 'Рис с овощами', brand: '', calories: 135, protein: 3.0, fat: 3.5, carbs: 23.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Рис по-тайски (жареный с яйцом)', brand: '', calories: 175, protein: 6.0, fat: 6.5, carbs: 24.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Плов с курицей', brand: '', calories: 180, protein: 8.0, fat: 7.0, carbs: 22.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Плов с говядиной', brand: '', calories: 210, protein: 9.5, fat: 9.0, carbs: 23.0, fiber: 0.8, isPublic: true, isVerified: true },
    { name: 'Плов со свининой', brand: '', calories: 240, protein: 8.5, fat: 12.0, carbs: 24.0, fiber: 0.7, isPublic: true, isVerified: true },
    { name: 'Овсянка на воде', brand: 'Ясно солнышко', calories: 88, protein: 3.0, fat: 1.7, carbs: 15.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Овсянка на молоке', brand: 'Ясно солнышко', calories: 102, protein: 3.2, fat: 4.1, carbs: 14.5, fiber: 1.2, isPublic: true, isVerified: true },
    { name: 'Овсянка с яблоком и корицей', brand: '', calories: 110, protein: 3.5, fat: 4.0, carbs: 16.5, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Овсянка с бананом', brand: '', calories: 130, protein: 4.0, fat: 4.5, carbs: 19.0, fiber: 2.2, isPublic: true, isVerified: true },
    { name: 'Овсянка с ягодами', brand: '', calories: 105, protein: 3.5, fat: 3.8, carbs: 15.5, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Овсяноблин', brand: '', calories: 180, protein: 10.0, fat: 8.0, carbs: 16.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Манная каша на молоке', brand: '', calories: 98, protein: 3.0, fat: 3.2, carbs: 15.3, fiber: 0.2, isPublic: true, isVerified: true },
    { name: 'Манная каша на воде', brand: '', calories: 75, protein: 2.5, fat: 0.2, carbs: 16.0, fiber: 0.2, isPublic: true, isVerified: true },
    { name: 'Пшённая каша на молоке', brand: '', calories: 110, protein: 3.5, fat: 3.5, carbs: 17.0, fiber: 0.8, isPublic: true, isVerified: true },
    { name: 'Пшённая каша с тыквой', brand: '', calories: 95, protein: 3.0, fat: 3.0, carbs: 15.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Перловка варёная', brand: '', calories: 109, protein: 3.1, fat: 0.4, carbs: 23.0, fiber: 3.8, isPublic: true, isVerified: true },
    { name: 'Перловка с грибами', brand: '', calories: 125, protein: 4.0, fat: 3.0, carbs: 21.0, fiber: 3.5, isPublic: true, isVerified: true },
    { name: 'Булгур варёный', brand: 'Мистраль', calories: 83, protein: 3.1, fat: 0.2, carbs: 18.6, fiber: 4.5, isPublic: true, isVerified: true },
    { name: 'Булгур с овощами', brand: '', calories: 105, protein: 3.8, fat: 3.0, carbs: 17.0, fiber: 4.0, isPublic: true, isVerified: true },
    { name: 'Киноа варёное', brand: 'Мистраль', calories: 120, protein: 4.4, fat: 1.9, carbs: 21.0, fiber: 2.8, isPublic: true, isVerified: true },
    { name: 'Кускус варёный', brand: 'Yelli', calories: 112, protein: 3.8, fat: 0.2, carbs: 23.0, fiber: 1.4, isPublic: true, isVerified: true },
    { name: 'Полба варёная', brand: '', calories: 127, protein: 5.5, fat: 0.9, carbs: 25.0, fiber: 3.8, isPublic: true, isVerified: true },
    { name: 'Макароны варёные (твёрдые сорта)', brand: 'Barilla', calories: 112, protein: 4.5, fat: 0.6, carbs: 23.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Макароны с сыром', brand: '', calories: 185, protein: 8.0, fat: 7.5, carbs: 22.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Макароны по-флотски', brand: '', calories: 220, protein: 12.0, fat: 10.0, carbs: 21.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Паста Карбонара', brand: '', calories: 280, protein: 12.0, fat: 16.0, carbs: 23.0, fiber: 1.2, isPublic: true, isVerified: true },
    { name: 'Паста Болоньезе', brand: '', calories: 190, protein: 10.0, fat: 7.0, carbs: 22.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Лазанья мясная', brand: '', calories: 240, protein: 14.0, fat: 12.0, carbs: 20.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Спагетти варёные', brand: 'Barilla', calories: 158, protein: 5.8, fat: 0.9, carbs: 31.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Гречневая лапша (соба)', brand: '', calories: 99, protein: 5.1, fat: 0.7, carbs: 21.4, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Фунчоза варёная', brand: '', calories: 80, protein: 0.2, fat: 0.1, carbs: 20.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Лапша удон', brand: '', calories: 130, protein: 4.5, fat: 0.5, carbs: 27.0, fiber: 0.8, isPublic: true, isVerified: true },
    { name: 'Лапша рамен', brand: 'Доширак', calories: 440, protein: 9.0, fat: 18.0, carbs: 60.0, fiber: 2.0, isPublic: true, isVerified: true },

    // ===== ХЛЕБ, ВЫПЕЧКА, СНЕКИ =====
    { name: 'Хлеб Бородинский', brand: 'Коломенское', calories: 200, protein: 6.8, fat: 1.3, carbs: 39.8, fiber: 6.5, isPublic: true, isVerified: true },
    { name: 'Хлеб белый пшеничный', brand: 'Коломенское', calories: 265, protein: 7.6, fat: 3.2, carbs: 50.0, fiber: 2.3, isPublic: true, isVerified: true },
    { name: 'Хлеб ржаной', brand: 'Коломенское', calories: 210, protein: 6.0, fat: 1.2, carbs: 42.0, fiber: 7.0, isPublic: true, isVerified: true },
    { name: 'Хлеб цельнозерновой', brand: 'Коломенское', calories: 247, protein: 10.0, fat: 3.4, carbs: 41.0, fiber: 7.0, isPublic: true, isVerified: true },
    { name: 'Хлеб бездрожжевой', brand: '', calories: 220, protein: 7.5, fat: 2.0, carbs: 43.0, fiber: 5.5, isPublic: true, isVerified: true },
    { name: 'Хлеб Дарницкий', brand: '', calories: 206, protein: 6.5, fat: 1.2, carbs: 41.0, fiber: 6.8, isPublic: true, isVerified: true },
    { name: 'Батон нарезной', brand: 'Коломенское', calories: 262, protein: 7.5, fat: 2.9, carbs: 51.0, fiber: 2.2, isPublic: true, isVerified: true },
    { name: 'Батон с маслом', brand: '', calories: 320, protein: 7.8, fat: 12.0, carbs: 50.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Лаваш тонкий', brand: '', calories: 277, protein: 9.0, fat: 2.0, carbs: 56.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Лаваш с сыром', brand: '', calories: 310, protein: 11.0, fat: 10.0, carbs: 45.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Пита', brand: '', calories: 255, protein: 8.0, fat: 1.5, carbs: 52.0, fiber: 2.2, isPublic: true, isVerified: true },
    { name: 'Хлебцы ржаные', brand: 'Dr. Körner', calories: 310, protein: 11.0, fat: 3.0, carbs: 60.0, fiber: 15.0, isPublic: true, isVerified: true },
    { name: 'Хлебцы гречневые', brand: 'Dr. Körner', calories: 290, protein: 10.0, fat: 2.5, carbs: 58.0, fiber: 14.0, isPublic: true, isVerified: true },
    { name: 'Хлебцы рисовые', brand: 'Dr. Körner', calories: 300, protein: 8.0, fat: 2.0, carbs: 62.0, fiber: 8.0, isPublic: true, isVerified: true },
    { name: 'Крекеры', brand: 'Tuc', calories: 430, protein: 8.0, fat: 13.0, carbs: 69.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Гренки чесночные', brand: '', calories: 380, protein: 10.0, fat: 12.0, carbs: 55.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Сухари панировочные', brand: '', calories: 350, protein: 10.0, fat: 2.0, carbs: 73.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Багет французский', brand: '', calories: 270, protein: 8.5, fat: 2.5, carbs: 53.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Чиабатта', brand: '', calories: 260, protein: 8.0, fat: 3.0, carbs: 50.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Круассан', brand: '', calories: 406, protein: 8.0, fat: 21.0, carbs: 46.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Круассан с шоколадом', brand: '', calories: 430, protein: 7.0, fat: 23.0, carbs: 48.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Булочка сдобная', brand: '', calories: 340, protein: 8.0, fat: 10.0, carbs: 55.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Булочка с маком', brand: '', calories: 330, protein: 8.5, fat: 9.0, carbs: 54.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Булочка с корицей', brand: '', calories: 350, protein: 7.5, fat: 11.0, carbs: 56.0, fiber: 1.8, isPublic: true, isVerified: true },

    // ===== МЯСО, ПТИЦА, СУБПРОДУКТЫ =====
    { name: 'Куриная грудка (запечённая)', brand: 'Петелинка', calories: 165, protein: 31.0, fat: 3.6, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриная грудка (варёная)', brand: 'Петелинка', calories: 153, protein: 30.0, fat: 3.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриная грудка (жареная на масле)', brand: '', calories: 195, protein: 29.0, fat: 8.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриное филе в панировке', brand: '', calories: 230, protein: 25.0, fat: 12.0, carbs: 6.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Куриное бедро (запечённое без кожи)', brand: 'Петелинка', calories: 177, protein: 24.0, fat: 8.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриное бедро (жареное с кожей)', brand: '', calories: 230, protein: 21.0, fat: 16.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриная голень (запечённая)', brand: '', calories: 170, protein: 22.0, fat: 9.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриные крылья (запечённые)', brand: '', calories: 203, protein: 22.0, fat: 12.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриные крылья BBQ', brand: '', calories: 260, protein: 20.0, fat: 17.0, carbs: 6.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриная печень (тушёная)', brand: '', calories: 136, protein: 20.0, fat: 5.5, carbs: 1.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриные сердечки (тушёные)', brand: '', calories: 160, protein: 16.0, fat: 10.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриные желудки (варёные)', brand: '', calories: 140, protein: 18.0, fat: 7.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Индейка филе (запечённое)', brand: 'Индилайт', calories: 135, protein: 28.0, fat: 2.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Индейка филе (варёное)', brand: 'Индилайт', calories: 130, protein: 27.0, fat: 2.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Индейка бедро (запечённое)', brand: '', calories: 165, protein: 23.0, fat: 8.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говядина варёная', brand: '', calories: 254, protein: 26.0, fat: 17.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говядина тушёная', brand: '', calories: 232, protein: 18.0, fat: 16.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говядина жареная', brand: '', calories: 280, protein: 25.0, fat: 20.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говяжий стейк', brand: '', calories: 270, protein: 26.0, fat: 18.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говяжий фарш (сырой)', brand: '', calories: 220, protein: 17.0, fat: 17.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Телятина варёная', brand: '', calories: 175, protein: 28.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свинина нежирная (варёная)', brand: '', calories: 245, protein: 25.0, fat: 15.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свинина жирная (жареная)', brand: '', calories: 350, protein: 20.0, fat: 30.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свиная отбивная (жареная)', brand: '', calories: 310, protein: 24.0, fat: 22.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свиные рёбрышки', brand: '', calories: 320, protein: 18.0, fat: 27.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Шашлык из свинины', brand: '', calories: 280, protein: 22.0, fat: 20.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Шашлык из курицы', brand: '', calories: 190, protein: 24.0, fat: 9.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Шашлык из баранины', brand: '', calories: 250, protein: 20.0, fat: 18.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Баранина тушёная', brand: '', calories: 243, protein: 20.0, fat: 18.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Баранина жареная', brand: '', calories: 290, protein: 22.0, fat: 22.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кролик тушёный', brand: '', calories: 170, protein: 25.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Утка запечённая', brand: '', calories: 300, protein: 17.0, fat: 26.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Гусь запечённый', brand: '', calories: 370, protein: 16.0, fat: 34.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Котлеты куриные (жареные)', brand: '', calories: 230, protein: 18.0, fat: 15.0, carbs: 8.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Котлеты куриные (паровые)', brand: '', calories: 170, protein: 20.0, fat: 8.0, carbs: 5.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Котлеты говяжьи (жареные)', brand: '', calories: 260, protein: 17.0, fat: 19.0, carbs: 9.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Котлеты свиные (жареные)', brand: '', calories: 290, protein: 15.0, fat: 24.0, carbs: 8.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Котлеты рыбные', brand: '', calories: 180, protein: 14.0, fat: 10.0, carbs: 10.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Тефтели с рисом', brand: '', calories: 200, protein: 12.0, fat: 11.0, carbs: 15.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Фрикадельки куриные', brand: '', calories: 160, protein: 16.0, fat: 8.0, carbs: 6.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Бефстроганов из говядины', brand: '', calories: 250, protein: 18.0, fat: 18.0, carbs: 5.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Гуляш из говядины', brand: '', calories: 200, protein: 16.0, fat: 12.0, carbs: 7.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Азу по-татарски', brand: '', calories: 210, protein: 15.0, fat: 14.0, carbs: 6.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Мясо по-французски', brand: '', calories: 310, protein: 20.0, fat: 22.0, carbs: 7.0, fiber: 0.5, isPublic: true, isVerified: true },

    // ===== КОЛБАСЫ, СОСИСКИ, ДЕЛИКАТЕСЫ =====
    { name: 'Колбаса Докторская', brand: 'Велком', calories: 257, protein: 13.0, fat: 22.0, carbs: 1.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Сервелат', brand: 'Велком', calories: 430, protein: 12.0, fat: 40.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Салями', brand: '', calories: 450, protein: 15.0, fat: 42.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Краковская', brand: '', calories: 380, protein: 14.0, fat: 35.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Молочная', brand: '', calories: 250, protein: 11.0, fat: 22.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Варёно-копчёная', brand: '', calories: 360, protein: 15.0, fat: 32.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сосиски молочные', brand: 'Велком', calories: 266, protein: 11.0, fat: 24.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сосиски говяжьи', brand: '', calories: 230, protein: 12.0, fat: 20.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сосиски куриные', brand: '', calories: 200, protein: 13.0, fat: 16.0, carbs: 1.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сардельки', brand: '', calories: 280, protein: 10.0, fat: 26.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Ветчина', brand: 'Черкизово', calories: 270, protein: 14.0, fat: 23.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Ветчина индейки', brand: '', calories: 130, protein: 20.0, fat: 5.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Бекон жареный', brand: '', calories: 541, protein: 12.0, fat: 42.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Грудинка копчёная', brand: '', calories: 500, protein: 10.0, fat: 50.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Карбонад', brand: '', calories: 160, protein: 22.0, fat: 8.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Буженина', brand: '', calories: 250, protein: 18.0, fat: 19.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Заливное из говядины', brand: '', calories: 90, protein: 12.0, fat: 4.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Холодец', brand: '', calories: 180, protein: 15.0, fat: 13.0, carbs: 1.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Паштет печёночный', brand: '', calories: 300, protein: 12.0, fat: 27.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тушёнка говяжья', brand: '', calories: 220, protein: 16.0, fat: 17.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тушёнка свиная', brand: '', calories: 350, protein: 13.0, fat: 33.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },

    // ===== РЫБА, МОРЕПРОДУКТЫ, ИКРА =====
    { name: 'Лосось слабосолёный', brand: 'Русское море', calories: 202, protein: 22.0, fat: 12.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Лосось запечённый', brand: '', calories: 208, protein: 23.0, fat: 13.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Лосось на пару', brand: '', calories: 190, protein: 24.0, fat: 10.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Форель запечённая', brand: '', calories: 148, protein: 20.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Форель слабосолёная', brand: '', calories: 160, protein: 19.0, fat: 9.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сёмга запечённая', brand: '', calories: 220, protein: 21.0, fat: 15.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Горбуша запечённая', brand: '', calories: 140, protein: 21.0, fat: 6.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Горбуша консервированная', brand: 'Доброфлот', calories: 136, protein: 21.0, fat: 5.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кета запечённая', brand: '', calories: 155, protein: 22.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Скумбрия копчёная', brand: 'Русское море', calories: 221, protein: 20.0, fat: 15.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Скумбрия запечённая', brand: '', calories: 190, protein: 19.0, fat: 13.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сельдь слабосолёная', brand: 'Русское море', calories: 217, protein: 18.0, fat: 16.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сельдь под шубой', brand: '', calories: 210, protein: 6.0, fat: 16.0, carbs: 10.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Сельдь маринованная', brand: '', calories: 190, protein: 17.0, fat: 13.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тунец консервированный в воде', brand: 'John West', calories: 116, protein: 26.0, fat: 0.8, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тунец консервированный в масле', brand: 'John West', calories: 198, protein: 24.0, fat: 10.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тунец свежий (стейк)', brand: '', calories: 130, protein: 27.0, fat: 1.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Минтай варёный', brand: '', calories: 79, protein: 17.0, fat: 1.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Минтай жареный', brand: '', calories: 130, protein: 15.0, fat: 7.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Треска варёная', brand: '', calories: 78, protein: 17.0, fat: 0.7, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Треска жареная', brand: '', calories: 125, protein: 15.0, fat: 5.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Пикша варёная', brand: '', calories: 82, protein: 18.0, fat: 0.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Хек варёный', brand: '', calories: 86, protein: 17.0, fat: 1.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Судак запечённый', brand: '', calories: 95, protein: 19.0, fat: 1.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Щука запечённая', brand: '', calories: 90, protein: 19.0, fat: 1.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Карп жареный', brand: '', calories: 180, protein: 17.0, fat: 11.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Карась жареный', brand: '', calories: 170, protein: 18.0, fat: 10.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Лещ вяленый', brand: '', calories: 220, protein: 40.0, fat: 5.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Корюшка жареная', brand: '', calories: 150, protein: 15.0, fat: 9.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Мойва жареная', brand: '', calories: 220, protein: 18.0, fat: 16.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Килька в томате', brand: '', calories: 180, protein: 14.0, fat: 12.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Шпроты в масле', brand: 'Рижские', calories: 363, protein: 17.0, fat: 32.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сайра консервированная', brand: '', calories: 220, protein: 18.0, fat: 16.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Печень трески', brand: '', calories: 613, protein: 4.0, fat: 66.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Креветки варёные', brand: '', calories: 99, protein: 20.0, fat: 1.2, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Креветки жареные', brand: '', calories: 140, protein: 18.0, fat: 6.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кальмар варёный', brand: '', calories: 92, protein: 18.0, fat: 2.2, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кальмар жареный', brand: '', calories: 150, protein: 16.0, fat: 7.0, carbs: 5.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Мидии варёные', brand: '', calories: 86, protein: 12.0, fat: 2.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Устрицы', brand: '', calories: 72, protein: 9.0, fat: 2.0, carbs: 4.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Крабовые палочки', brand: 'Vici', calories: 88, protein: 6.0, fat: 0.5, carbs: 15.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Крабовое мясо', brand: '', calories: 82, protein: 16.0, fat: 1.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Морской коктейль', brand: '', calories: 85, protein: 15.0, fat: 1.5, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Икра красная', brand: '', calories: 245, protein: 32.0, fat: 13.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Икра чёрная', brand: '', calories: 280, protein: 24.0, fat: 18.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Икра минтая', brand: '', calories: 130, protein: 20.0, fat: 5.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Рыбные палочки', brand: '', calories: 200, protein: 12.0, fat: 10.0, carbs: 16.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Рыба в кляре', brand: '', calories: 230, protein: 16.0, fat: 12.0, carbs: 15.0, fiber: 0.5, isPublic: true, isVerified: true },
  ];

  for (const product of products) {
    await prisma.foodItem.create({ data: product });
  }

  console.log(`✅ Добавлено ${products.length} продуктов!`);
}

main()
  .catch((e) => console.error('❌ Ошибка:', e))
  .finally(() => prisma.$disconnect());