import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Очищаем старые продукты...');
  await prisma.mealEntry.deleteMany();
  await prisma.meal.deleteMany();
  await prisma.foodItem.deleteMany();

  console.log('Добавляем 1000+ продуктов...');

  const products = [
    // ===== КРУПЫ, КАШИ, МАКАРОНЫ (35) =====
    { name: 'Гречка ядрица (варёная)', brand: 'Увелка', calories: 110, protein: 4.2, fat: 1.1, carbs: 20.6, fiber: 2.7, isPublic: true, isVerified: true },
    { name: 'Гречка зелёная (варёная)', brand: 'Образ жизни', calories: 105, protein: 4.0, fat: 1.0, carbs: 19.5, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Гречка с грибами', brand: '', calories: 130, protein: 5.5, fat: 3.5, carbs: 19.0, fiber: 2.2, isPublic: true, isVerified: true },
    { name: 'Рис белый варёный', brand: 'Мистраль', calories: 116, protein: 2.2, fat: 0.5, carbs: 25.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Рис бурый варёный', brand: 'Мистраль', calories: 112, protein: 2.6, fat: 0.9, carbs: 23.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Рис дикий варёный', brand: 'Мистраль', calories: 101, protein: 4.0, fat: 0.3, carbs: 21.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Рис басмати варёный', brand: 'Мистраль', calories: 120, protein: 2.4, fat: 0.4, carbs: 26.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Рис жасмин варёный', brand: 'Мистраль', calories: 118, protein: 2.3, fat: 0.3, carbs: 26.5, fiber: 0.4, isPublic: true, isVerified: true },
    { name: 'Рис красный варёный', brand: '', calories: 110, protein: 2.5, fat: 0.5, carbs: 24.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Рис чёрный варёный', brand: '', calories: 105, protein: 3.0, fat: 0.5, carbs: 22.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Овсянка на воде', brand: 'Ясно солнышко', calories: 88, protein: 3.0, fat: 1.7, carbs: 15.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Овсянка на молоке', brand: 'Ясно солнышко', calories: 102, protein: 3.2, fat: 4.1, carbs: 14.5, fiber: 1.2, isPublic: true, isVerified: true },
    { name: 'Овсянка быстрого приготовления', brand: 'Ясно солнышко', calories: 370, protein: 12.0, fat: 6.0, carbs: 62.0, fiber: 7.0, isPublic: true, isVerified: true },
    { name: 'Манная каша на молоке', brand: '', calories: 98, protein: 3.0, fat: 3.2, carbs: 15.3, fiber: 0.2, isPublic: true, isVerified: true },
    { name: 'Манная каша на воде', brand: '', calories: 75, protein: 2.5, fat: 0.2, carbs: 16.0, fiber: 0.2, isPublic: true, isVerified: true },
    { name: 'Пшённая каша на молоке', brand: '', calories: 110, protein: 3.5, fat: 3.5, carbs: 17.0, fiber: 0.8, isPublic: true, isVerified: true },
    { name: 'Пшённая каша на воде', brand: '', calories: 90, protein: 3.0, fat: 0.7, carbs: 17.0, fiber: 0.8, isPublic: true, isVerified: true },
    { name: 'Перловка варёная', brand: '', calories: 109, protein: 3.1, fat: 0.4, carbs: 23.0, fiber: 3.8, isPublic: true, isVerified: true },
    { name: 'Булгур варёный', brand: 'Мистраль', calories: 83, protein: 3.1, fat: 0.2, carbs: 18.6, fiber: 4.5, isPublic: true, isVerified: true },
    { name: 'Киноа варёное', brand: 'Мистраль', calories: 120, protein: 4.4, fat: 1.9, carbs: 21.0, fiber: 2.8, isPublic: true, isVerified: true },
    { name: 'Кускус варёный', brand: 'Yelli', calories: 112, protein: 3.8, fat: 0.2, carbs: 23.0, fiber: 1.4, isPublic: true, isVerified: true },
    { name: 'Полба варёная', brand: '', calories: 127, protein: 5.5, fat: 0.9, carbs: 25.0, fiber: 3.8, isPublic: true, isVerified: true },
    { name: 'Макароны варёные (твёрдые сорта)', brand: 'Barilla', calories: 112, protein: 4.5, fat: 0.6, carbs: 23.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Макароны цельнозерновые варёные', brand: 'Barilla', calories: 124, protein: 5.0, fat: 0.8, carbs: 25.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Спагетти варёные', brand: 'Barilla', calories: 158, protein: 5.8, fat: 0.9, carbs: 31.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Вермишель варёная', brand: '', calories: 140, protein: 4.5, fat: 0.5, carbs: 28.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Лапша яичная варёная', brand: '', calories: 138, protein: 5.0, fat: 2.5, carbs: 25.0, fiber: 0.8, isPublic: true, isVerified: true },
    { name: 'Лапша удон', brand: '', calories: 130, protein: 4.5, fat: 0.5, carbs: 27.0, fiber: 0.8, isPublic: true, isVerified: true },
    { name: 'Фунчоза варёная', brand: '', calories: 80, protein: 0.2, fat: 0.1, carbs: 20.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Гречневая лапша (соба)', brand: '', calories: 99, protein: 5.1, fat: 0.7, carbs: 21.4, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Рисовая лапша варёная', brand: '', calories: 109, protein: 2.0, fat: 0.2, carbs: 25.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Макароны безглютеновые варёные', brand: '', calories: 150, protein: 3.0, fat: 1.0, carbs: 32.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Пшеничная крупа варёная', brand: '', calories: 105, protein: 3.5, fat: 0.5, carbs: 22.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Ячневая крупа варёная', brand: '', calories: 100, protein: 3.0, fat: 0.5, carbs: 21.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Кукурузная каша', brand: '', calories: 120, protein: 3.0, fat: 1.5, carbs: 24.0, fiber: 1.5, isPublic: true, isVerified: true },

    // ===== ХЛЕБ, ВЫПЕЧКА (25) =====
    { name: 'Хлеб Бородинский', brand: 'Коломенское', calories: 200, protein: 6.8, fat: 1.3, carbs: 39.8, fiber: 6.5, isPublic: true, isVerified: true },
    { name: 'Хлеб белый пшеничный', brand: 'Коломенское', calories: 265, protein: 7.6, fat: 3.2, carbs: 50.0, fiber: 2.3, isPublic: true, isVerified: true },
    { name: 'Хлеб ржаной', brand: 'Коломенское', calories: 210, protein: 6.0, fat: 1.2, carbs: 42.0, fiber: 7.0, isPublic: true, isVerified: true },
    { name: 'Хлеб цельнозерновой', brand: 'Коломенское', calories: 247, protein: 10.0, fat: 3.4, carbs: 41.0, fiber: 7.0, isPublic: true, isVerified: true },
    { name: 'Хлеб бездрожжевой', brand: '', calories: 220, protein: 7.5, fat: 2.0, carbs: 43.0, fiber: 5.5, isPublic: true, isVerified: true },
    { name: 'Хлеб Дарницкий', brand: '', calories: 206, protein: 6.5, fat: 1.2, carbs: 41.0, fiber: 6.8, isPublic: true, isVerified: true },
    { name: 'Батон нарезной', brand: 'Коломенское', calories: 262, protein: 7.5, fat: 2.9, carbs: 51.0, fiber: 2.2, isPublic: true, isVerified: true },
    { name: 'Лаваш тонкий', brand: '', calories: 277, protein: 9.0, fat: 2.0, carbs: 56.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Лаваш толстый', brand: '', calories: 290, protein: 8.5, fat: 3.0, carbs: 54.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Пита', brand: '', calories: 255, protein: 8.0, fat: 1.5, carbs: 52.0, fiber: 2.2, isPublic: true, isVerified: true },
    { name: 'Хлебцы ржаные', brand: 'Dr. Körner', calories: 310, protein: 11.0, fat: 3.0, carbs: 60.0, fiber: 15.0, isPublic: true, isVerified: true },
    { name: 'Хлебцы гречневые', brand: 'Dr. Körner', calories: 290, protein: 10.0, fat: 2.5, carbs: 58.0, fiber: 14.0, isPublic: true, isVerified: true },
    { name: 'Хлебцы рисовые', brand: 'Dr. Körner', calories: 300, protein: 8.0, fat: 2.0, carbs: 62.0, fiber: 8.0, isPublic: true, isVerified: true },
    { name: 'Хлебцы пшеничные', brand: '', calories: 320, protein: 10.0, fat: 2.0, carbs: 65.0, fiber: 6.0, isPublic: true, isVerified: true },
    { name: 'Багет французский', brand: '', calories: 270, protein: 8.5, fat: 2.5, carbs: 53.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Чиабатта', brand: '', calories: 260, protein: 8.0, fat: 3.0, carbs: 50.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Круассан', brand: '', calories: 406, protein: 8.0, fat: 21.0, carbs: 46.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Круассан с шоколадом', brand: '', calories: 430, protein: 7.0, fat: 23.0, carbs: 48.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Булочка сдобная', brand: '', calories: 340, protein: 8.0, fat: 10.0, carbs: 55.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Булочка с корицей', brand: '', calories: 350, protein: 7.5, fat: 11.0, carbs: 56.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Булочка с маком', brand: '', calories: 330, protein: 8.5, fat: 9.0, carbs: 54.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Крекеры', brand: 'Tuc', calories: 430, protein: 8.0, fat: 13.0, carbs: 69.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Гренки чесночные', brand: '', calories: 380, protein: 10.0, fat: 12.0, carbs: 55.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Сухари панировочные', brand: '', calories: 350, protein: 10.0, fat: 2.0, carbs: 73.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Тортилья пшеничная', brand: '', calories: 300, protein: 8.0, fat: 6.0, carbs: 52.0, fiber: 2.5, isPublic: true, isVerified: true },

    // ===== МЯСО, ПТИЦА, СУБПРОДУКТЫ (50) =====
    { name: 'Куриная грудка (варёная)', brand: 'Петелинка', calories: 153, protein: 30.0, fat: 3.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриная грудка (запечённая)', brand: 'Петелинка', calories: 165, protein: 31.0, fat: 3.6, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриная грудка (жареная на масле)', brand: '', calories: 195, protein: 29.0, fat: 8.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриное филе (сырое)', brand: '', calories: 113, protein: 23.0, fat: 2.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриное бедро (запечённое без кожи)', brand: 'Петелинка', calories: 177, protein: 24.0, fat: 8.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриное бедро (жареное с кожей)', brand: '', calories: 230, protein: 21.0, fat: 16.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриная голень (запечённая)', brand: '', calories: 170, protein: 22.0, fat: 9.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриные крылья (запечённые)', brand: '', calories: 203, protein: 22.0, fat: 12.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриные крылья BBQ', brand: '', calories: 260, protein: 20.0, fat: 17.0, carbs: 6.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриная печень (сырая)', brand: '', calories: 119, protein: 17.0, fat: 5.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриная печень (тушёная)', brand: '', calories: 136, protein: 20.0, fat: 5.5, carbs: 1.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриные сердечки (сырые)', brand: '', calories: 153, protein: 15.0, fat: 10.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриные желудки (варёные)', brand: '', calories: 140, protein: 18.0, fat: 7.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Куриный фарш (сырой)', brand: '', calories: 143, protein: 17.0, fat: 8.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Индейка филе (сырая)', brand: 'Индилайт', calories: 114, protein: 24.0, fat: 2.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Индейка филе (запечённое)', brand: 'Индилайт', calories: 135, protein: 28.0, fat: 2.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Индейка филе (варёное)', brand: 'Индилайт', calories: 130, protein: 27.0, fat: 2.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Индейка бедро (запечённое)', brand: '', calories: 165, protein: 23.0, fat: 8.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Индейка фарш (сырой)', brand: '', calories: 150, protein: 18.0, fat: 8.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говядина вырезка (сырая)', brand: '', calories: 187, protein: 19.0, fat: 12.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говядина варёная', brand: '', calories: 254, protein: 26.0, fat: 17.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говядина тушёная', brand: '', calories: 232, protein: 18.0, fat: 16.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говядина жареная', brand: '', calories: 280, protein: 25.0, fat: 20.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говяжий фарш (сырой)', brand: '', calories: 220, protein: 17.0, fat: 17.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говяжья печень (сырая)', brand: '', calories: 127, protein: 18.0, fat: 3.5, carbs: 5.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Говяжий язык (варёный)', brand: '', calories: 224, protein: 16.0, fat: 16.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Телятина варёная', brand: '', calories: 175, protein: 28.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свинина вырезка (сырая)', brand: '', calories: 242, protein: 21.0, fat: 17.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свинина нежирная (варёная)', brand: '', calories: 245, protein: 25.0, fat: 15.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свинина жирная (жареная)', brand: '', calories: 350, protein: 20.0, fat: 30.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свиная отбивная (жареная)', brand: '', calories: 310, protein: 24.0, fat: 22.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свиные рёбрышки (сырые)', brand: '', calories: 277, protein: 16.0, fat: 23.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Свиной фарш (сырой)', brand: '', calories: 263, protein: 17.0, fat: 21.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Баранина (сырая)', brand: '', calories: 209, protein: 16.0, fat: 16.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Баранина тушёная', brand: '', calories: 243, protein: 20.0, fat: 18.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Баранина жареная', brand: '', calories: 290, protein: 22.0, fat: 22.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кролик (сырой)', brand: '', calories: 136, protein: 21.0, fat: 5.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кролик тушёный', brand: '', calories: 170, protein: 25.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Утка (сырая)', brand: '', calories: 346, protein: 12.0, fat: 33.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Утка запечённая', brand: '', calories: 300, protein: 17.0, fat: 26.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Гусь (сырой)', brand: '', calories: 371, protein: 15.0, fat: 34.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Перепелка (сырая)', brand: '', calories: 134, protein: 21.0, fat: 4.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Конина (сырая)', brand: '', calories: 167, protein: 20.0, fat: 9.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Оленина (сырая)', brand: '', calories: 155, protein: 20.0, fat: 8.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },

    // ===== КОЛБАСЫ, СОСИСКИ, ДЕЛИКАТЕСЫ (30) =====
    { name: 'Колбаса Докторская', brand: 'Велком', calories: 257, protein: 13.0, fat: 22.0, carbs: 1.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Сервелат', brand: 'Велком', calories: 430, protein: 12.0, fat: 40.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Салями', brand: '', calories: 450, protein: 15.0, fat: 42.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Краковская', brand: '', calories: 380, protein: 14.0, fat: 35.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Молочная', brand: '', calories: 250, protein: 11.0, fat: 22.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Варёно-копчёная', brand: '', calories: 360, protein: 15.0, fat: 32.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Полукопчёная', brand: '', calories: 400, protein: 13.0, fat: 38.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Ливерная', brand: '', calories: 326, protein: 12.0, fat: 30.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сосиски молочные', brand: 'Велком', calories: 266, protein: 11.0, fat: 24.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сосиски говяжьи', brand: '', calories: 230, protein: 12.0, fat: 20.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сосиски куриные', brand: '', calories: 200, protein: 13.0, fat: 16.0, carbs: 1.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сардельки', brand: '', calories: 280, protein: 10.0, fat: 26.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Ветчина', brand: 'Черкизово', calories: 270, protein: 14.0, fat: 23.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Ветчина индейки', brand: '', calories: 130, protein: 20.0, fat: 5.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Ветчина куриная', brand: '', calories: 120, protein: 18.0, fat: 5.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Бекон сырой', brand: '', calories: 541, protein: 12.0, fat: 42.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Бекон жареный', brand: '', calories: 541, protein: 12.0, fat: 42.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Грудинка копчёная', brand: '', calories: 500, protein: 10.0, fat: 50.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Карбонад', brand: '', calories: 160, protein: 22.0, fat: 8.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Буженина', brand: '', calories: 250, protein: 18.0, fat: 19.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Заливное из говядины', brand: '', calories: 90, protein: 12.0, fat: 4.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Холодец', brand: '', calories: 180, protein: 15.0, fat: 13.0, carbs: 1.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Паштет печёночный', brand: '', calories: 300, protein: 12.0, fat: 27.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тушёнка говяжья', brand: '', calories: 220, protein: 16.0, fat: 17.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тушёнка свиная', brand: '', calories: 350, protein: 13.0, fat: 33.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаса Охотничья', brand: '', calories: 460, protein: 25.0, fat: 40.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Шейка свиная копчёная', brand: '', calories: 480, protein: 15.0, fat: 46.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Балык из свинины', brand: '', calories: 350, protein: 20.0, fat: 30.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Колбаски охотничьи', brand: '', calories: 440, protein: 22.0, fat: 38.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Шпик солёный', brand: '', calories: 800, protein: 1.5, fat: 89.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
      // ===== РЫБА, МОРЕПРОДУКТЫ (45) =====
    { name: 'Лосось атлантический (сырой)', brand: '', calories: 208, protein: 20.0, fat: 13.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Лосось слабосолёный', brand: 'Русское море', calories: 202, protein: 22.0, fat: 12.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Лосось запечённый', brand: '', calories: 208, protein: 23.0, fat: 13.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Лосось копчёный', brand: '', calories: 220, protein: 22.0, fat: 14.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Форель радужная (сырая)', brand: '', calories: 148, protein: 20.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Форель запечённая', brand: '', calories: 148, protein: 20.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Форель слабосолёная', brand: '', calories: 160, protein: 19.0, fat: 9.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сёмга (сырая)', brand: '', calories: 220, protein: 20.0, fat: 15.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Горбуша (сырая)', brand: '', calories: 140, protein: 21.0, fat: 6.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Горбуша запечённая', brand: '', calories: 140, protein: 21.0, fat: 6.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Горбуша консервированная', brand: 'Доброфлот', calories: 136, protein: 21.0, fat: 5.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кета (сырая)', brand: '', calories: 155, protein: 22.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Скумбрия (сырая)', brand: '', calories: 205, protein: 18.0, fat: 14.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Скумбрия копчёная', brand: 'Русское море', calories: 221, protein: 20.0, fat: 15.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Скумбрия запечённая', brand: '', calories: 190, protein: 19.0, fat: 13.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сельдь (сырая)', brand: '', calories: 217, protein: 18.0, fat: 16.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сельдь слабосолёная', brand: 'Русское море', calories: 217, protein: 18.0, fat: 16.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сельдь маринованная', brand: '', calories: 190, protein: 17.0, fat: 13.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тунец (сырой)', brand: '', calories: 130, protein: 27.0, fat: 1.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тунец консервированный в воде', brand: 'John West', calories: 116, protein: 26.0, fat: 0.8, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тунец консервированный в масле', brand: 'John West', calories: 198, protein: 24.0, fat: 10.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Минтай (сырой)', brand: '', calories: 79, protein: 17.0, fat: 1.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Минтай варёный', brand: '', calories: 79, protein: 17.0, fat: 1.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Минтай жареный', brand: '', calories: 130, protein: 15.0, fat: 7.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Треска (сырая)', brand: '', calories: 78, protein: 17.0, fat: 0.7, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Треска варёная', brand: '', calories: 78, protein: 17.0, fat: 0.7, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Пикша (сырая)', brand: '', calories: 82, protein: 18.0, fat: 0.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Хек (сырой)', brand: '', calories: 86, protein: 17.0, fat: 1.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Судак (сырой)', brand: '', calories: 95, protein: 19.0, fat: 1.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Щука (сырая)', brand: '', calories: 90, protein: 19.0, fat: 1.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Окунь морской (сырой)', brand: '', calories: 94, protein: 18.0, fat: 2.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Карп (сырой)', brand: '', calories: 127, protein: 17.0, fat: 5.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Карась (сырой)', brand: '', calories: 102, protein: 17.0, fat: 3.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Лещ (сырой)', brand: '', calories: 105, protein: 17.0, fat: 3.5, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Мойва (сырая)', brand: '', calories: 116, protein: 13.0, fat: 7.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Килька (сырая)', brand: '', calories: 135, protein: 14.0, fat: 8.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Килька в томате', brand: '', calories: 180, protein: 14.0, fat: 12.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Шпроты в масле', brand: 'Рижские', calories: 363, protein: 17.0, fat: 32.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сайра консервированная', brand: '', calories: 220, protein: 18.0, fat: 16.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Печень трески', brand: '', calories: 613, protein: 4.0, fat: 66.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Креветки (сырые)', brand: '', calories: 99, protein: 20.0, fat: 1.2, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Креветки варёные', brand: '', calories: 99, protein: 20.0, fat: 1.2, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Креветки жареные', brand: '', calories: 140, protein: 18.0, fat: 6.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кальмар (сырой)', brand: '', calories: 92, protein: 18.0, fat: 2.2, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Мидии варёные', brand: '', calories: 86, protein: 12.0, fat: 2.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Крабовые палочки', brand: 'Vici', calories: 88, protein: 6.0, fat: 0.5, carbs: 15.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Икра красная', brand: '', calories: 245, protein: 32.0, fat: 13.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Икра чёрная', brand: '', calories: 280, protein: 24.0, fat: 18.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Икра минтая', brand: '', calories: 130, protein: 20.0, fat: 5.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Морской коктейль', brand: '', calories: 85, protein: 15.0, fat: 1.5, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },

    // ===== МОЛОЧНЫЕ ПРОДУКТЫ (35) =====
    { name: 'Молоко 3.2%', brand: 'Домик в деревне', calories: 60, protein: 2.9, fat: 3.2, carbs: 4.7, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Молоко 2.5%', brand: 'Домик в деревне', calories: 52, protein: 2.8, fat: 2.5, carbs: 4.8, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Молоко 1.5%', brand: 'Домик в деревне', calories: 45, protein: 2.8, fat: 1.5, carbs: 4.8, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Молоко 0.5%', brand: 'Домик в деревне', calories: 36, protein: 3.0, fat: 0.5, carbs: 4.9, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Молоко топлёное', brand: '', calories: 67, protein: 2.9, fat: 4.0, carbs: 4.8, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Молоко козье', brand: '', calories: 69, protein: 3.5, fat: 4.1, carbs: 4.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Молоко соевое', brand: 'Nemoloko', calories: 40, protein: 3.0, fat: 1.5, carbs: 3.5, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Молоко миндальное', brand: 'Nemoloko', calories: 25, protein: 0.5, fat: 1.5, carbs: 2.5, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Молоко кокосовое', brand: 'Aroy-D', calories: 185, protein: 2.0, fat: 19.0, carbs: 2.8, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Молоко овсяное', brand: 'Nemoloko', calories: 45, protein: 1.0, fat: 1.5, carbs: 7.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Сливки 10%', brand: '', calories: 118, protein: 2.7, fat: 10.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сливки 20%', brand: '', calories: 206, protein: 2.5, fat: 20.0, carbs: 3.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сливки 33%', brand: '', calories: 322, protein: 2.2, fat: 33.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кефир 3.2%', brand: 'Домик в деревне', calories: 59, protein: 2.8, fat: 3.2, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кефир 2.5%', brand: 'Домик в деревне', calories: 53, protein: 2.9, fat: 2.5, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кефир 1%', brand: 'Домик в деревне', calories: 40, protein: 3.0, fat: 1.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Бифидок', brand: '', calories: 55, protein: 3.0, fat: 2.5, carbs: 4.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Ряженка 2.5%', brand: 'Домик в деревне', calories: 54, protein: 2.9, fat: 2.5, carbs: 4.2, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Снежок', brand: 'Домик в деревне', calories: 72, protein: 2.7, fat: 2.5, carbs: 10.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Простокваша', brand: '', calories: 58, protein: 3.0, fat: 2.5, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Ацидофилин', brand: '', calories: 50, protein: 3.0, fat: 2.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Тан', brand: '', calories: 24, protein: 1.5, fat: 1.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Айран', brand: '', calories: 27, protein: 1.5, fat: 1.2, carbs: 2.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Творог 0%', brand: 'Простоквашино', calories: 103, protein: 22.0, fat: 0.6, carbs: 3.3, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Творог 5%', brand: 'Простоквашино', calories: 145, protein: 21.0, fat: 5.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Творог 9%', brand: 'Простоквашино', calories: 169, protein: 18.0, fat: 9.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Творог 18%', brand: '', calories: 236, protein: 15.0, fat: 18.0, carbs: 2.8, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Творог зернёный', brand: 'Простоквашино', calories: 110, protein: 12.0, fat: 5.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Творожная масса с изюмом', brand: '', calories: 230, protein: 10.0, fat: 12.0, carbs: 20.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Сметана 10%', brand: 'Простоквашино', calories: 115, protein: 2.7, fat: 10.0, carbs: 3.9, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сметана 15%', brand: 'Простоквашино', calories: 162, protein: 2.6, fat: 15.0, carbs: 3.6, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сметана 20%', brand: 'Простоквашино', calories: 206, protein: 2.5, fat: 20.0, carbs: 3.4, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сметана 30%', brand: '', calories: 293, protein: 2.3, fat: 30.0, carbs: 3.1, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Йогурт натуральный 2%', brand: 'Активиа', calories: 60, protein: 4.5, fat: 2.0, carbs: 6.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Йогурт греческий', brand: '', calories: 66, protein: 9.0, fat: 2.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Йогурт питьевой 1.5%', brand: 'Активиа', calories: 50, protein: 3.5, fat: 1.5, carbs: 6.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Йогурт с фруктами', brand: 'Чудо', calories: 90, protein: 3.0, fat: 1.5, carbs: 16.0, fiber: 0.3, isPublic: true, isVerified: true },

    // ===== ЯЙЦА (10) =====
    { name: 'Яйцо куриное (сырое)', brand: '', calories: 157, protein: 12.7, fat: 11.5, carbs: 0.7, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Яйцо куриное варёное', brand: 'Роскар', calories: 158, protein: 12.7, fat: 11.5, carbs: 0.7, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Яйцо куриное жареное', brand: '', calories: 196, protein: 12.5, fat: 15.5, carbs: 0.8, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Белок яичный (сырой)', brand: '', calories: 48, protein: 11.0, fat: 0, carbs: 0.7, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Желток яичный (сырой)', brand: '', calories: 322, protein: 16.0, fat: 28.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Яйцо перепелиное', brand: '', calories: 168, protein: 13.0, fat: 13.0, carbs: 0.6, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Яйцо утиное', brand: '', calories: 185, protein: 13.0, fat: 14.0, carbs: 0.7, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Яйцо гусиное', brand: '', calories: 185, protein: 13.0, fat: 13.0, carbs: 1.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Яичный порошок', brand: '', calories: 542, protein: 46.0, fat: 38.0, carbs: 4.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Омлет из 2 яиц на молоке', brand: '', calories: 180, protein: 13.0, fat: 14.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
      // ===== ОВОЩИ, ЗЕЛЕНЬ (60) =====
    { name: 'Огурец свежий', brand: '', calories: 15, protein: 0.8, fat: 0.1, carbs: 2.5, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Огурец солёный', brand: '', calories: 12, protein: 0.8, fat: 0.1, carbs: 1.8, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Огурец маринованный', brand: '', calories: 16, protein: 0.8, fat: 0.1, carbs: 2.5, fiber: 0.8, isPublic: true, isVerified: true },
    { name: 'Помидор свежий', brand: '', calories: 20, protein: 1.1, fat: 0.2, carbs: 3.7, fiber: 1.2, isPublic: true, isVerified: true },
    { name: 'Помидоры черри', brand: '', calories: 18, protein: 0.9, fat: 0.2, carbs: 3.5, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Томатная паста', brand: '', calories: 82, protein: 4.5, fat: 0.5, carbs: 18.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Болгарский перец красный', brand: '', calories: 27, protein: 1.3, fat: 0.2, carbs: 5.3, fiber: 1.7, isPublic: true, isVerified: true },
    { name: 'Болгарский перец жёлтый', brand: '', calories: 25, protein: 1.0, fat: 0.2, carbs: 5.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Перец чили', brand: '', calories: 40, protein: 1.9, fat: 0.4, carbs: 8.8, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Морковь свежая', brand: '', calories: 35, protein: 1.3, fat: 0.1, carbs: 6.9, fiber: 2.4, isPublic: true, isVerified: true },
    { name: 'Морковь варёная', brand: '', calories: 33, protein: 1.2, fat: 0.1, carbs: 6.5, fiber: 2.2, isPublic: true, isVerified: true },
    { name: 'Морковь по-корейски', brand: '', calories: 110, protein: 1.5, fat: 8.0, carbs: 9.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Свёкла свежая', brand: '', calories: 43, protein: 1.6, fat: 0.2, carbs: 8.8, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Свёкла варёная', brand: '', calories: 44, protein: 1.7, fat: 0.2, carbs: 8.8, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Капуста белокочанная свежая', brand: '', calories: 25, protein: 1.3, fat: 0.1, carbs: 4.7, fiber: 2.3, isPublic: true, isVerified: true },
    { name: 'Капуста тушёная', brand: '', calories: 50, protein: 2.0, fat: 2.5, carbs: 5.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Капуста квашеная', brand: '', calories: 20, protein: 1.8, fat: 0.1, carbs: 2.2, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Капуста краснокочанная', brand: '', calories: 26, protein: 1.5, fat: 0.1, carbs: 5.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Капуста цветная свежая', brand: '', calories: 25, protein: 1.9, fat: 0.3, carbs: 5.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Капуста цветная варёная', brand: '', calories: 23, protein: 1.8, fat: 0.3, carbs: 4.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Капуста брюссельская', brand: '', calories: 43, protein: 3.4, fat: 0.3, carbs: 9.0, fiber: 3.8, isPublic: true, isVerified: true },
    { name: 'Брокколи свежая', brand: '', calories: 34, protein: 2.8, fat: 0.4, carbs: 7.0, fiber: 2.6, isPublic: true, isVerified: true },
    { name: 'Брокколи варёная', brand: '', calories: 35, protein: 2.4, fat: 0.4, carbs: 7.0, fiber: 3.3, isPublic: true, isVerified: true },
    { name: 'Картофель сырой', brand: '', calories: 77, protein: 2.0, fat: 0.4, carbs: 16.3, fiber: 1.4, isPublic: true, isVerified: true },
    { name: 'Картофель варёный', brand: '', calories: 82, protein: 2.0, fat: 0.4, carbs: 16.7, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Картофель жареный', brand: '', calories: 192, protein: 2.8, fat: 9.5, carbs: 23.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Картофель фри', brand: '', calories: 312, protein: 3.5, fat: 15.0, carbs: 41.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Картофельное пюре на молоке', brand: '', calories: 106, protein: 2.5, fat: 4.2, carbs: 14.0, fiber: 1.3, isPublic: true, isVerified: true },
    { name: 'Батат сырой', brand: '', calories: 86, protein: 1.6, fat: 0.1, carbs: 20.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Батат запечённый', brand: '', calories: 90, protein: 2.0, fat: 0.1, carbs: 21.0, fiber: 3.3, isPublic: true, isVerified: true },
    { name: 'Кабачок свежий', brand: '', calories: 17, protein: 0.6, fat: 0.3, carbs: 3.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Кабачок тушёный', brand: '', calories: 24, protein: 0.6, fat: 0.3, carbs: 4.6, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Баклажан свежий', brand: '', calories: 25, protein: 1.0, fat: 0.2, carbs: 5.9, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Баклажан запечённый', brand: '', calories: 35, protein: 1.0, fat: 0.2, carbs: 6.5, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Тыква сырая', brand: '', calories: 26, protein: 1.0, fat: 0.1, carbs: 6.5, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Тыква запечённая', brand: '', calories: 26, protein: 1.0, fat: 0.1, carbs: 4.4, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Кукуруза сырая', brand: '', calories: 86, protein: 3.3, fat: 1.4, carbs: 19.0, fiber: 2.7, isPublic: true, isVerified: true },
    { name: 'Кукуруза варёная', brand: '', calories: 123, protein: 4.1, fat: 2.3, carbs: 22.0, fiber: 2.7, isPublic: true, isVerified: true },
    { name: 'Кукуруза консервированная', brand: 'Бондюэль', calories: 86, protein: 3.2, fat: 1.5, carbs: 15.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Горошек зелёный свежий', brand: '', calories: 81, protein: 5.4, fat: 0.4, carbs: 14.5, fiber: 5.0, isPublic: true, isVerified: true },
    { name: 'Горошек зелёный консервированный', brand: 'Бондюэль', calories: 55, protein: 4.0, fat: 0.3, carbs: 9.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Фасоль стручковая свежая', brand: '', calories: 31, protein: 1.8, fat: 0.2, carbs: 7.0, fiber: 3.4, isPublic: true, isVerified: true },
    { name: 'Фасоль красная консервированная', brand: 'Бондюэль', calories: 90, protein: 6.0, fat: 0.5, carbs: 15.0, fiber: 5.0, isPublic: true, isVerified: true },
    { name: 'Фасоль белая варёная', brand: '', calories: 139, protein: 9.0, fat: 0.5, carbs: 25.0, fiber: 6.0, isPublic: true, isVerified: true },
    { name: 'Нут варёный', brand: '', calories: 164, protein: 9.0, fat: 2.6, carbs: 27.0, fiber: 7.6, isPublic: true, isVerified: true },
    { name: 'Чечевица варёная', brand: '', calories: 116, protein: 9.0, fat: 0.4, carbs: 20.0, fiber: 7.9, isPublic: true, isVerified: true },
    { name: 'Маш варёный', brand: '', calories: 105, protein: 7.0, fat: 0.4, carbs: 19.0, fiber: 7.6, isPublic: true, isVerified: true },
    { name: 'Лук репчатый свежий', brand: '', calories: 40, protein: 1.1, fat: 0.1, carbs: 8.2, fiber: 1.7, isPublic: true, isVerified: true },
    { name: 'Лук зелёный', brand: '', calories: 32, protein: 1.8, fat: 0.2, carbs: 7.0, fiber: 2.6, isPublic: true, isVerified: true },
    { name: 'Лук порей', brand: '', calories: 61, protein: 1.5, fat: 0.3, carbs: 14.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Чеснок', brand: '', calories: 149, protein: 6.4, fat: 0.5, carbs: 30.0, fiber: 2.1, isPublic: true, isVerified: true },
    { name: 'Укроп свежий', brand: '', calories: 43, protein: 3.5, fat: 1.1, carbs: 4.9, fiber: 2.1, isPublic: true, isVerified: true },
    { name: 'Петрушка свежая', brand: '', calories: 47, protein: 3.7, fat: 0.4, carbs: 7.6, fiber: 2.1, isPublic: true, isVerified: true },
    { name: 'Кинза', brand: '', calories: 23, protein: 2.0, fat: 0.5, carbs: 3.7, fiber: 2.8, isPublic: true, isVerified: true },
    { name: 'Базилик', brand: '', calories: 23, protein: 3.2, fat: 0.6, carbs: 2.7, fiber: 1.6, isPublic: true, isVerified: true },
    { name: 'Шпинат', brand: '', calories: 23, protein: 2.9, fat: 0.4, carbs: 3.6, fiber: 2.2, isPublic: true, isVerified: true },
    { name: 'Щавель', brand: '', calories: 22, protein: 2.0, fat: 0.3, carbs: 3.2, fiber: 2.9, isPublic: true, isVerified: true },
    { name: 'Сельдерей стебли', brand: '', calories: 14, protein: 0.7, fat: 0.1, carbs: 3.0, fiber: 1.6, isPublic: true, isVerified: true },
    { name: 'Сельдерей корень', brand: '', calories: 42, protein: 1.5, fat: 0.3, carbs: 9.2, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Салат листовой', brand: '', calories: 15, protein: 1.2, fat: 0.3, carbs: 2.0, fiber: 1.3, isPublic: true, isVerified: true },
    { name: 'Салат Айсберг', brand: '', calories: 14, protein: 0.9, fat: 0.1, carbs: 3.0, fiber: 1.2, isPublic: true, isVerified: true },
    { name: 'Руккола', brand: '', calories: 25, protein: 2.6, fat: 0.7, carbs: 3.7, fiber: 1.6, isPublic: true, isVerified: true },
    { name: 'Редис', brand: '', calories: 16, protein: 0.7, fat: 0.1, carbs: 3.4, fiber: 1.6, isPublic: true, isVerified: true },
    { name: 'Редька чёрная', brand: '', calories: 36, protein: 1.5, fat: 0.2, carbs: 7.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Дайкон', brand: '', calories: 18, protein: 0.6, fat: 0.1, carbs: 4.1, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Хрен', brand: '', calories: 59, protein: 3.2, fat: 0.4, carbs: 11.0, fiber: 3.3, isPublic: true, isVerified: true },
    { name: 'Имбирь корень', brand: '', calories: 80, protein: 1.8, fat: 0.8, carbs: 17.8, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Спаржа', brand: '', calories: 20, protein: 2.2, fat: 0.1, carbs: 3.9, fiber: 2.1, isPublic: true, isVerified: true },
    { name: 'Артишок', brand: '', calories: 47, protein: 3.3, fat: 0.2, carbs: 10.5, fiber: 5.4, isPublic: true, isVerified: true },
    { name: 'Оливки зелёные', brand: '', calories: 145, protein: 1.0, fat: 15.0, carbs: 4.0, fiber: 3.3, isPublic: true, isVerified: true },
    { name: 'Маслины чёрные', brand: '', calories: 115, protein: 1.0, fat: 11.0, carbs: 6.0, fiber: 3.2, isPublic: true, isVerified: true },
      // ===== ФРУКТЫ, ЯГОДЫ (50) =====
    { name: 'Яблоко красное', brand: '', calories: 52, protein: 0.3, fat: 0.2, carbs: 14.0, fiber: 2.4, isPublic: true, isVerified: true },
    { name: 'Яблоко зелёное', brand: '', calories: 47, protein: 0.4, fat: 0.4, carbs: 9.8, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Банан', brand: '', calories: 96, protein: 1.5, fat: 0.5, carbs: 21.0, fiber: 1.7, isPublic: true, isVerified: true },
    { name: 'Апельсин', brand: '', calories: 47, protein: 0.9, fat: 0.1, carbs: 12.0, fiber: 2.4, isPublic: true, isVerified: true },
    { name: 'Мандарин', brand: '', calories: 53, protein: 0.8, fat: 0.3, carbs: 13.0, fiber: 1.8, isPublic: true, isVerified: true },
    { name: 'Грейпфрут', brand: '', calories: 42, protein: 0.8, fat: 0.1, carbs: 11.0, fiber: 1.6, isPublic: true, isVerified: true },
    { name: 'Лимон', brand: '', calories: 29, protein: 1.1, fat: 0.3, carbs: 9.0, fiber: 2.8, isPublic: true, isVerified: true },
    { name: 'Лайм', brand: '', calories: 30, protein: 0.7, fat: 0.2, carbs: 11.0, fiber: 2.8, isPublic: true, isVerified: true },
    { name: 'Груша', brand: '', calories: 57, protein: 0.4, fat: 0.1, carbs: 15.0, fiber: 3.1, isPublic: true, isVerified: true },
    { name: 'Виноград', brand: '', calories: 69, protein: 0.7, fat: 0.2, carbs: 17.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Киви', brand: '', calories: 61, protein: 1.1, fat: 0.5, carbs: 15.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Хурма', brand: '', calories: 67, protein: 0.5, fat: 0.4, carbs: 16.0, fiber: 1.6, isPublic: true, isVerified: true },
    { name: 'Гранат', brand: '', calories: 83, protein: 1.7, fat: 0.6, carbs: 19.0, fiber: 4.0, isPublic: true, isVerified: true },
    { name: 'Клубника', brand: '', calories: 32, protein: 0.8, fat: 0.4, carbs: 7.5, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Малина', brand: '', calories: 52, protein: 1.2, fat: 0.7, carbs: 11.0, fiber: 6.5, isPublic: true, isVerified: true },
    { name: 'Черника', brand: '', calories: 57, protein: 0.7, fat: 0.3, carbs: 14.0, fiber: 2.4, isPublic: true, isVerified: true },
    { name: 'Ежевика', brand: '', calories: 43, protein: 1.4, fat: 0.5, carbs: 10.0, fiber: 5.3, isPublic: true, isVerified: true },
    { name: 'Вишня', brand: '', calories: 50, protein: 1.0, fat: 0.3, carbs: 12.0, fiber: 1.7, isPublic: true, isVerified: true },
    { name: 'Черешня', brand: '', calories: 63, protein: 1.1, fat: 0.4, carbs: 16.0, fiber: 2.1, isPublic: true, isVerified: true },
    { name: 'Слива', brand: '', calories: 46, protein: 0.7, fat: 0.3, carbs: 11.0, fiber: 1.4, isPublic: true, isVerified: true },
    { name: 'Персик', brand: '', calories: 39, protein: 0.9, fat: 0.3, carbs: 9.5, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Абрикос', brand: '', calories: 48, protein: 1.4, fat: 0.4, carbs: 11.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Нектарин', brand: '', calories: 44, protein: 1.1, fat: 0.3, carbs: 11.0, fiber: 1.7, isPublic: true, isVerified: true },
    { name: 'Арбуз', brand: '', calories: 30, protein: 0.6, fat: 0.2, carbs: 7.5, fiber: 0.4, isPublic: true, isVerified: true },
    { name: 'Дыня', brand: '', calories: 34, protein: 0.8, fat: 0.2, carbs: 8.0, fiber: 0.9, isPublic: true, isVerified: true },
    { name: 'Авокадо', brand: '', calories: 160, protein: 2.0, fat: 15.0, carbs: 9.0, fiber: 6.7, isPublic: true, isVerified: true },
    { name: 'Ананас', brand: '', calories: 50, protein: 0.5, fat: 0.1, carbs: 13.0, fiber: 1.4, isPublic: true, isVerified: true },
    { name: 'Манго', brand: '', calories: 60, protein: 0.8, fat: 0.4, carbs: 15.0, fiber: 1.6, isPublic: true, isVerified: true },
    { name: 'Папайя', brand: '', calories: 43, protein: 0.5, fat: 0.3, carbs: 11.0, fiber: 1.7, isPublic: true, isVerified: true },
    { name: 'Кокос', brand: '', calories: 354, protein: 3.3, fat: 33.0, carbs: 15.0, fiber: 9.0, isPublic: true, isVerified: true },
    { name: 'Финики', brand: '', calories: 282, protein: 2.5, fat: 0.5, carbs: 75.0, fiber: 8.0, isPublic: true, isVerified: true },
    { name: 'Инжир', brand: '', calories: 74, protein: 0.8, fat: 0.3, carbs: 19.0, fiber: 2.9, isPublic: true, isVerified: true },
    { name: 'Изюм', brand: '', calories: 299, protein: 3.0, fat: 0.5, carbs: 79.0, fiber: 3.7, isPublic: true, isVerified: true },
    { name: 'Курага', brand: '', calories: 241, protein: 3.4, fat: 0.5, carbs: 63.0, fiber: 7.3, isPublic: true, isVerified: true },
    { name: 'Чернослив', brand: '', calories: 240, protein: 2.2, fat: 0.4, carbs: 64.0, fiber: 7.1, isPublic: true, isVerified: true },
    { name: 'Клюква', brand: '', calories: 46, protein: 0.4, fat: 0.1, carbs: 12.0, fiber: 4.6, isPublic: true, isVerified: true },
    { name: 'Брусника', brand: '', calories: 46, protein: 0.7, fat: 0.5, carbs: 10.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Облепиха', brand: '', calories: 82, protein: 1.2, fat: 5.4, carbs: 10.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Крыжовник', brand: '', calories: 44, protein: 0.9, fat: 0.6, carbs: 10.0, fiber: 4.3, isPublic: true, isVerified: true },
    { name: 'Смородина чёрная', brand: '', calories: 63, protein: 1.4, fat: 0.4, carbs: 15.0, fiber: 4.8, isPublic: true, isVerified: true },
    { name: 'Смородина красная', brand: '', calories: 56, protein: 1.4, fat: 0.2, carbs: 14.0, fiber: 4.3, isPublic: true, isVerified: true },

    // ===== ОРЕХИ, СЕМЕНА (20) =====
    { name: 'Орехи грецкие', brand: '', calories: 654, protein: 15.0, fat: 65.0, carbs: 14.0, fiber: 6.7, isPublic: true, isVerified: true },
    { name: 'Миндаль', brand: '', calories: 579, protein: 21.0, fat: 50.0, carbs: 22.0, fiber: 12.5, isPublic: true, isVerified: true },
    { name: 'Арахис', brand: '', calories: 567, protein: 26.0, fat: 49.0, carbs: 16.0, fiber: 8.5, isPublic: true, isVerified: true },
    { name: 'Кешью', brand: '', calories: 553, protein: 18.0, fat: 44.0, carbs: 30.0, fiber: 3.3, isPublic: true, isVerified: true },
    { name: 'Фисташки', brand: '', calories: 560, protein: 20.0, fat: 45.0, carbs: 27.0, fiber: 10.0, isPublic: true, isVerified: true },
    { name: 'Фундук', brand: '', calories: 628, protein: 15.0, fat: 61.0, carbs: 17.0, fiber: 9.7, isPublic: true, isVerified: true },
    { name: 'Кедровые орехи', brand: '', calories: 673, protein: 14.0, fat: 68.0, carbs: 13.0, fiber: 3.7, isPublic: true, isVerified: true },
    { name: 'Макадамия', brand: '', calories: 718, protein: 8.0, fat: 76.0, carbs: 14.0, fiber: 8.6, isPublic: true, isVerified: true },
    { name: 'Пекан', brand: '', calories: 691, protein: 9.0, fat: 72.0, carbs: 14.0, fiber: 9.6, isPublic: true, isVerified: true },
    { name: 'Бразильский орех', brand: '', calories: 659, protein: 14.0, fat: 67.0, carbs: 12.0, fiber: 7.5, isPublic: true, isVerified: true },
    { name: 'Семечки подсолнечника', brand: 'Бабкины', calories: 584, protein: 21.0, fat: 51.0, carbs: 20.0, fiber: 8.6, isPublic: true, isVerified: true },
    { name: 'Семечки тыквенные', brand: '', calories: 541, protein: 25.0, fat: 46.0, carbs: 13.0, fiber: 4.5, isPublic: true, isVerified: true },
    { name: 'Семена льна', brand: '', calories: 534, protein: 18.0, fat: 42.0, carbs: 29.0, fiber: 27.0, isPublic: true, isVerified: true },
    { name: 'Семена чиа', brand: '', calories: 486, protein: 17.0, fat: 31.0, carbs: 42.0, fiber: 34.0, isPublic: true, isVerified: true },
    { name: 'Семена кунжута', brand: '', calories: 573, protein: 17.0, fat: 50.0, carbs: 23.0, fiber: 12.0, isPublic: true, isVerified: true },
    { name: 'Кокосовая стружка', brand: '', calories: 660, protein: 7.0, fat: 65.0, carbs: 24.0, fiber: 16.0, isPublic: true, isVerified: true },
    { name: 'Арахисовая паста', brand: '', calories: 588, protein: 25.0, fat: 50.0, carbs: 20.0, fiber: 6.0, isPublic: true, isVerified: true },
    { name: 'Козинаки из семечек', brand: '', calories: 515, protein: 15.0, fat: 30.0, carbs: 45.0, fiber: 5.0, isPublic: true, isVerified: true },

    // ===== ГРИБЫ (15) =====
    { name: 'Шампиньоны свежие', brand: '', calories: 27, protein: 3.1, fat: 0.3, carbs: 3.3, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Шампиньоны жареные', brand: '', calories: 80, protein: 3.5, fat: 6.0, carbs: 3.5, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Белые грибы свежие', brand: '', calories: 34, protein: 3.7, fat: 1.7, carbs: 3.4, fiber: 2.3, isPublic: true, isVerified: true },
    { name: 'Лисички', brand: '', calories: 19, protein: 1.5, fat: 1.0, carbs: 1.0, fiber: 7.0, isPublic: true, isVerified: true },
    { name: 'Опята', brand: '', calories: 22, protein: 2.2, fat: 0.7, carbs: 2.5, fiber: 5.0, isPublic: true, isVerified: true },
    { name: 'Вешенки', brand: '', calories: 38, protein: 3.3, fat: 0.4, carbs: 6.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Подосиновики', brand: '', calories: 31, protein: 3.2, fat: 0.7, carbs: 3.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Подберёзовики', brand: '', calories: 30, protein: 3.0, fat: 0.5, carbs: 3.5, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Маслята', brand: '', calories: 25, protein: 2.5, fat: 1.0, carbs: 2.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Сыроежки', brand: '', calories: 20, protein: 2.0, fat: 0.5, carbs: 2.5, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Грузди', brand: '', calories: 18, protein: 1.8, fat: 0.5, carbs: 2.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Рыжики', brand: '', calories: 22, protein: 2.0, fat: 0.5, carbs: 2.5, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Сморчки', brand: '', calories: 27, protein: 2.5, fat: 0.5, carbs: 3.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Трюфель', brand: '', calories: 50, protein: 6.0, fat: 0.5, carbs: 5.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Шиитаке', brand: '', calories: 34, protein: 2.2, fat: 0.5, carbs: 6.8, fiber: 2.5, isPublic: true, isVerified: true },
      // ===== СЛАДОСТИ, СНЕКИ (35) =====
    { name: 'Шоколад молочный', brand: 'Алёнка', calories: 538, protein: 5.7, fat: 31.5, carbs: 57.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Шоколад горький 70%', brand: '', calories: 539, protein: 6.2, fat: 35.4, carbs: 48.0, fiber: 7.0, isPublic: true, isVerified: true },
    { name: 'Шоколад белый', brand: '', calories: 539, protein: 5.5, fat: 32.0, carbs: 59.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Зефир классический', brand: 'Шармэль', calories: 320, protein: 0.8, fat: 0.1, carbs: 79.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Мармелад', brand: '', calories: 296, protein: 0.4, fat: 0.1, carbs: 76.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Мёд натуральный', brand: 'Медовый край', calories: 304, protein: 0.3, fat: 0, carbs: 82.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сахар-песок', brand: '', calories: 399, protein: 0, fat: 0, carbs: 99.8, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Печенье Юбилейное', brand: '', calories: 463, protein: 7.5, fat: 19.0, carbs: 65.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Пряники', brand: '', calories: 364, protein: 6.0, fat: 8.0, carbs: 72.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Вафли', brand: '', calories: 539, protein: 5.0, fat: 28.0, carbs: 65.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Мороженое пломбир', brand: '', calories: 230, protein: 3.5, fat: 15.0, carbs: 20.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Мороженое эскимо', brand: '', calories: 270, protein: 4.0, fat: 20.0, carbs: 22.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Сорбет', brand: '', calories: 120, protein: 0.5, fat: 0, carbs: 28.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Чипсы картофельные', brand: "Lay's", calories: 536, protein: 5.0, fat: 34.0, carbs: 53.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Чипсы кукурузные', brand: '', calories: 480, protein: 7.0, fat: 25.0, carbs: 60.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Попкорн солёный', brand: '', calories: 407, protein: 8.0, fat: 14.0, carbs: 64.0, fiber: 8.0, isPublic: true, isVerified: true },
    { name: 'Попкорн сладкий', brand: '', calories: 480, protein: 5.0, fat: 20.0, carbs: 68.0, fiber: 5.0, isPublic: true, isVerified: true },
    { name: 'Сухарики ржаные', brand: '', calories: 380, protein: 10.0, fat: 8.0, carbs: 65.0, fiber: 5.0, isPublic: true, isVerified: true },
    { name: 'Халва подсолнечная', brand: '', calories: 516, protein: 12.0, fat: 30.0, carbs: 55.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Батончик мюсли', brand: '', calories: 370, protein: 6.0, fat: 8.0, carbs: 68.0, fiber: 5.0, isPublic: true, isVerified: true },
    { name: 'Батончик протеиновый', brand: '', calories: 380, protein: 20.0, fat: 10.0, carbs: 50.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Конфеты шоколадные', brand: '', calories: 500, protein: 5.0, fat: 28.0, carbs: 60.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Карамель леденцовая', brand: '', calories: 380, protein: 0, fat: 0, carbs: 95.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Ирис', brand: '', calories: 400, protein: 3.0, fat: 10.0, carbs: 76.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Варенье клубничное', brand: '', calories: 260, protein: 0.3, fat: 0, carbs: 65.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Джем абрикосовый', brand: '', calories: 250, protein: 0.5, fat: 0, carbs: 62.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Шоколадная паста', brand: 'Nutella', calories: 539, protein: 6.0, fat: 31.0, carbs: 57.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Печенье овсяное', brand: '', calories: 440, protein: 6.0, fat: 15.0, carbs: 70.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Крекеры солёные', brand: '', calories: 430, protein: 8.0, fat: 13.0, carbs: 69.0, fiber: 2.5, isPublic: true, isVerified: true },

    // ===== СОУСЫ, ПРИПРАВЫ, МАСЛА (25) =====
    { name: 'Подсолнечное масло', brand: 'Олейна', calories: 899, protein: 0, fat: 99.9, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Оливковое масло', brand: 'Borges', calories: 884, protein: 0, fat: 100.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Сливочное масло 82.5%', brand: 'Вологодское', calories: 748, protein: 0.5, fat: 82.5, carbs: 0.8, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кокосовое масло', brand: '', calories: 862, protein: 0, fat: 100.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Льняное масло', brand: '', calories: 884, protein: 0, fat: 100.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кунжутное масло', brand: '', calories: 884, protein: 0, fat: 100.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Майонез классический', brand: 'Махеев', calories: 616, protein: 2.0, fat: 67.0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Майонез лёгкий', brand: '', calories: 300, protein: 1.0, fat: 30.0, carbs: 8.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кетчуп томатный', brand: 'Махеев', calories: 102, protein: 1.5, fat: 0.2, carbs: 24.0, fiber: 0.7, isPublic: true, isVerified: true },
    { name: 'Соевый соус', brand: 'Kikkoman', calories: 53, protein: 10.0, fat: 0, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Горчица', brand: '', calories: 162, protein: 5.5, fat: 9.0, carbs: 15.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Уксус столовый', brand: '', calories: 18, protein: 0, fat: 0, carbs: 0.9, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Уксус яблочный', brand: '', calories: 21, protein: 0, fat: 0, carbs: 0.9, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Уксус бальзамический', brand: '', calories: 88, protein: 0.5, fat: 0, carbs: 17.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Соль поваренная', brand: '', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Перец чёрный молотый', brand: '', calories: 251, protein: 10.0, fat: 3.3, carbs: 64.0, fiber: 26.0, isPublic: true, isVerified: true },
    { name: 'Паприка молотая', brand: '', calories: 282, protein: 14.0, fat: 13.0, carbs: 54.0, fiber: 35.0, isPublic: true, isVerified: true },
    { name: 'Куркума', brand: '', calories: 354, protein: 8.0, fat: 10.0, carbs: 65.0, fiber: 22.0, isPublic: true, isVerified: true },
    { name: 'Корица', brand: '', calories: 247, protein: 4.0, fat: 1.2, carbs: 81.0, fiber: 53.0, isPublic: true, isVerified: true },
    { name: 'Ванильный сахар', brand: '', calories: 398, protein: 0, fat: 0, carbs: 99.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Томатная паста', brand: '', calories: 82, protein: 4.5, fat: 0.5, carbs: 18.0, fiber: 2.5, isPublic: true, isVerified: true },
    { name: 'Хрен столовый', brand: '', calories: 59, protein: 3.2, fat: 0.4, carbs: 11.0, fiber: 3.3, isPublic: true, isVerified: true },
    { name: 'Аджика', brand: '', calories: 55, protein: 2.0, fat: 2.5, carbs: 7.0, fiber: 1.5, isPublic: true, isVerified: true },
    { name: 'Соус терияки', brand: '', calories: 120, protein: 4.0, fat: 0.5, carbs: 25.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Соус барбекю', brand: '', calories: 130, protein: 1.5, fat: 0.5, carbs: 30.0, fiber: 1.0, isPublic: true, isVerified: true },

    // ===== НАПИТКИ (30) =====
    { name: 'Вода питьевая', brand: '', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Чай чёрный без сахара', brand: '', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Чай зелёный без сахара', brand: '', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кофе чёрный без сахара', brand: '', calories: 2, protein: 0.1, fat: 0, carbs: 0.3, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кофе с молоком (латте)', brand: '', calories: 56, protein: 3.0, fat: 2.5, carbs: 5.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Капучино без сахара', brand: '', calories: 45, protein: 2.5, fat: 2.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Эспрессо', brand: '', calories: 9, protein: 0.2, fat: 0.2, carbs: 1.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Американо', brand: '', calories: 2, protein: 0.1, fat: 0, carbs: 0.3, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Какао на молоке', brand: '', calories: 85, protein: 3.5, fat: 3.0, carbs: 11.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Сок апельсиновый', brand: 'J7', calories: 45, protein: 0.7, fat: 0.2, carbs: 10.0, fiber: 0.2, isPublic: true, isVerified: true },
    { name: 'Сок яблочный', brand: 'J7', calories: 46, protein: 0.5, fat: 0.1, carbs: 11.0, fiber: 0.2, isPublic: true, isVerified: true },
    { name: 'Сок томатный', brand: 'J7', calories: 21, protein: 0.8, fat: 0.1, carbs: 4.2, fiber: 0.4, isPublic: true, isVerified: true },
    { name: 'Сок гранатовый', brand: '', calories: 54, protein: 0.2, fat: 0.1, carbs: 13.0, fiber: 0.3, isPublic: true, isVerified: true },
    { name: 'Сок вишнёвый', brand: '', calories: 50, protein: 0.4, fat: 0.1, carbs: 12.0, fiber: 0.5, isPublic: true, isVerified: true },
    { name: 'Морс клюквенный', brand: '', calories: 35, protein: 0.1, fat: 0, carbs: 8.5, fiber: 0.2, isPublic: true, isVerified: true },
    { name: 'Компот из сухофруктов', brand: '', calories: 50, protein: 0.3, fat: 0, carbs: 12.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'Квас', brand: 'Очаковский', calories: 27, protein: 0.2, fat: 0, carbs: 5.2, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Кола', brand: '', calories: 42, protein: 0, fat: 0, carbs: 10.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Лимонад', brand: '', calories: 38, protein: 0, fat: 0, carbs: 9.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Энергетик', brand: '', calories: 45, protein: 0, fat: 0, carbs: 11.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Пиво светлое 4.5%', brand: '', calories: 43, protein: 0.5, fat: 0, carbs: 3.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Вино красное сухое', brand: '', calories: 68, protein: 0.1, fat: 0, carbs: 2.5, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Вино белое сухое', brand: '', calories: 66, protein: 0.1, fat: 0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Водка', brand: '', calories: 235, protein: 0, fat: 0, carbs: 0.1, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Коньяк', brand: '', calories: 239, protein: 0, fat: 0, carbs: 0.1, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Шампанское', brand: '', calories: 85, protein: 0.1, fat: 0, carbs: 5.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Молочный коктейль', brand: '', calories: 120, protein: 3.5, fat: 4.0, carbs: 18.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Смузи ягодный', brand: '', calories: 60, protein: 1.0, fat: 0.5, carbs: 14.0, fiber: 3.0, isPublic: true, isVerified: true },
    { name: 'Протеиновый коктейль на воде', brand: '', calories: 120, protein: 25.0, fat: 1.5, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },

    // ===== СПОРТПИТ, БАДы (15) =====
    { name: 'Протеин сывороточный (1 порция 30г)', brand: '', calories: 120, protein: 24.0, fat: 1.5, carbs: 3.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Протеин соевый (1 порция 30г)', brand: '', calories: 110, protein: 22.0, fat: 1.0, carbs: 4.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Гейнер (1 порция 100г)', brand: '', calories: 380, protein: 15.0, fat: 3.0, carbs: 74.0, fiber: 1.0, isPublic: true, isVerified: true },
    { name: 'BCAA (1 порция 5г)', brand: '', calories: 20, protein: 5.0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Креатин моногидрат (5г)', brand: '', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'L-карнитин (1 порция)', brand: '', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Предтренировочный комплекс (1 порция)', brand: '', calories: 10, protein: 0, fat: 0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Витамин D (1 капсула)', brand: '', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Омега-3 (1 капсула)', brand: '', calories: 10, protein: 0, fat: 1.0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Магний (1 таблетка)', brand: '', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Протеиновый батончик', brand: '', calories: 200, protein: 20.0, fat: 6.0, carbs: 18.0, fiber: 2.0, isPublic: true, isVerified: true },
    { name: 'Изотоник', brand: '', calories: 25, protein: 0, fat: 0, carbs: 6.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Казеин (1 порция 30г)', brand: '', calories: 110, protein: 24.0, fat: 1.0, carbs: 2.0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Глютамин (5г)', brand: '', calories: 20, protein: 5.0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
    { name: 'Цинк (1 таблетка)', brand: '', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, isPublic: true, isVerified: true },
  ];

  for (const product of products) {
    await prisma.foodItem.create({ data: product });
  }

  console.log(`✅ Добавлено ${products.length} продуктов!`);
}

main()
  .catch((e) => console.error('❌ Ошибка:', e))
  .finally(() => prisma.$disconnect());